eventos/urls.py
from django.urls import path
from . import views

app_name = 'eventos'

urlpatterns = [
    
    path('',views.index,name='index'),
    
    #ACCIONES DE USUARIO
    path('iniciarsesion/',views.login,name='iniciarsesion'),
    path('registrar/',views.signup,name='registrar'),
    path('cerrarsesion/', views.cerrar_sesion, name='cerrar_sesion'),
    
    #ACCIONES DE EVENTO
    path('eventos/',views.evento,name='eventos'),
    path('miseventos/', views.mis_eventos, name='mis_eventos'),
    path('actualizarMiEvento/', views.actualizar_mi_evento, name='actualizar_mi_evento'),
    path('detalle_evento/eliminarMiEvento/<int:evento_codigo>/',views.eliminar_mi_evento,name='eliminar_mi_evento'),
     
    path('detalle_evento/<int:evento_codigo>/',views.detalle_evento,name='detalle_evento'),
    path('agregarEvento/',views.agregar_evento,name='agregar_evento'),
    path('detalle_evento/eliminarEvento/<int:evento_codigo>/',views.eliminar_evento,name='eliminar_evento'),
    path('actualizarEvento/', views.actualizar_evento, name='actualizar_evento'),

    #ACCIONES DE REGISTRO DE USUARIO EN EVENTO
    path('registrar_usuario_evento/', views.registrar_usuario_evento, name='registrar_usuario_evento'),
    path('agregar_usuario_evento/', views.agregar_usuario_evento, name='agregar_usuario_evento'),
    path('eliminar_usuario_evento/<int:evento_codigo>/<int:usuario_codigo>/', views.eliminar_usuario_evento, name='eliminar_usuario_evento'),
    
]

lab07/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eventos/',include('eventos.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

eventos/models.py
from django.db import models

class Usuario(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    contraseña = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre + " " + self.apellido

class Evento(models.Model):
    codigo = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100)
    encargado = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="eventos")
    fecha_evento = models.DateField('Fecha de evento')
    hora_evento = models.TimeField('Hora de evento') 
    descripcion = models.TextField()
    
    def __str__(self):
        return self.titulo
    
class RegistroEvento(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_registro = models.DateTimeField('Fecha de registro', auto_now_add=True)

    def __str__(self):
        return str(self.usuario) + " registrado en " + str(self.evento)

eventos/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Usuario,Evento,RegistroEvento
from django.contrib import messages
from .decorators import verificar_autenticacion
import calendar
from datetime import datetime
from django.db.models import Count

def index(request):
    
    if 'usuario_id' in request.session:
        usuario_id = request.session['usuario_id']
        try:
            usuario = Usuario.objects.get(codigo=usuario_id)
        except Usuario.DoesNotExist:
            pass
    return render(request, 'index.html')

#ACCIONES USUARIO

def signup(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        email = request.POST.get('email')
        contraseña = request.POST.get('contraseña')
        
        if Usuario.objects.filter(email=email).exists():
            messages.error(request, 'El usuario con este correo electrónico ya existe.')
            return render(request, 'register.html')
        
        Usuario.objects.create(nombre=nombre, apellido=apellido, email=email, contraseña=contraseña)
        
        return redirect('/eventos/iniciarsesion')
    else:
        return render(request, 'register.html')


def login(request):
    
    email = request.POST.get('email')
    contraseña = request.POST.get('contraseña')
        
    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        if usuario.contraseña == contraseña:
            request.session['usuario_id'] = usuario.codigo  
            return redirect('/eventos/eventos')
        else:
            messages.error(request, 'Contraseña incorrecta.')
            return render(request, 'login.html')
            
    else:
        if Usuario.DoesNotExist:
            messages.error(request, 'La cuenta no existe.')
            return render(request, 'login.html')

    return render(request, 'login.html')

def cerrar_sesion(request):
    if 'usuario_id' in request.session:
        del request.session['usuario_id']
    return redirect('/eventos/iniciarsesion/')


#ACCIONES EVENTO

@verificar_autenticacion
def evento(request):
    usuario_id = request.session['usuario_id']
    usuario = Usuario.objects.get(codigo=usuario_id)
    evento_lista = Evento.objects.all()
    
    #CONSULTA AVANZADA (CANTIDAD DE EVENTOS EN EL MES)
    actual = datetime.now()
    primer_dia_mes_actual = datetime(actual.year, actual.month, 1)
    ultimo_dia_mes_actual = datetime(actual.year, actual.month, calendar.monthrange(actual.year, actual.month)[1])

    eventos_mes_actual = Evento.objects.filter(fecha_evento__gte=primer_dia_mes_actual, fecha_evento__lte=ultimo_dia_mes_actual)
    cantidad_eventos_mes_actual = eventos_mes_actual.count()
    #CONSULTA AVANZADA (CANTIDAD DE EVENTOS EN EL MES)
    
    #CONSULTA AVANZADA (USUARIOS CON MAYOR PARTICIPACION)
    usuarios_mas_registrados = Usuario.objects.annotate(num_registros=Count('registroevento')).order_by('-num_registros')
    #CONSULTA AVANZADA (USUARIO CON MAYOR PARTICIPACION)
    
    for evento in evento_lista:
        if usuario == evento.encargado:
            evento.es_encargado = True
        else:
            evento.es_encargado = False

    context = {
        'evento_lista': evento_lista,
        'usuario': usuario,
        'cantidad_eventos_mes_actual': cantidad_eventos_mes_actual,
        'usuarios_mas_registrados': usuarios_mas_registrados,
    }
    return render(request, 'eventos.html', context)

@verificar_autenticacion
def agregar_evento(request):
    titulo = request.POST['titulo']
    encargado_id = request.POST['encargado']  
    encargado = Usuario.objects.get(codigo=encargado_id)  
    imagen = request.FILES['imagen']
    fecha_evento = request.POST['fecha_evento']
    hora_evento = request.POST['hora_evento']
    descripcion = request.POST['descripcion']
    
    Evento.objects.create(titulo=titulo, encargado=encargado, imagen=imagen, fecha_evento=fecha_evento, hora_evento=hora_evento, descripcion=descripcion)
        
    return redirect('/eventos/eventos')

@verificar_autenticacion
def detalle_evento(request, evento_codigo):
    usuario_id = request.session['usuario_id']
    usuario = Usuario.objects.get(codigo=usuario_id)
    evento = get_object_or_404(Evento, codigo=evento_codigo)
    usuario_lista = Usuario.objects.all()
    
    registros_evento = RegistroEvento.objects.filter(evento=evento)
    
    usuarios_registrados = [registro.usuario for registro in registros_evento]
    
    #CONSULTA AVANZADA (CANTIDAD DE USUARIOS REGISTRADOS EN EL EVENTO)
    cantidad_usuarios_registrados = len(usuarios_registrados)
    #CONSULTA AVANZADA (CANTIDAD DE USUARIOS REGISTRADOS EN EL EVENTO)
    
    if usuario == evento.encargado:
        es_encargado = True
    else:
        es_encargado = False

    context = {
        'evento': evento,
        'es_encargado': es_encargado,
        'usuario': usuario,
        'usuario_lista':usuario_lista,
        'usuarios_registrados': usuarios_registrados,
        'cantidad_usuarios_registrados': cantidad_usuarios_registrados,
    }
    
    return render(request, 'detalleEvento.html', context)

@verificar_autenticacion
def actualizar_evento(request):
    codigo = request.POST.get('codigo')
    titulo = request.POST['titulo']
    encargado_id = request.POST['encargado']
    encargado = Usuario.objects.get(codigo=encargado_id)

    if 'imagen' in request.FILES:
        imagen = request.FILES['imagen']
    else:
        evento = Evento.objects.get(codigo=codigo)
        imagen = evento.imagen  

    fecha_evento = request.POST['fecha_evento']
    hora_evento = request.POST['hora_evento']
    descripcion = request.POST['descripcion']

    evento = Evento.objects.get(codigo=codigo)

    evento.titulo = titulo
    evento.encargado = encargado
    evento.imagen = imagen
    evento.fecha_evento = fecha_evento
    evento.hora_evento = hora_evento
    evento.descripcion = descripcion

    evento.save()

    return redirect('/eventos/detalle_evento/{}/'.format(codigo))

@verificar_autenticacion 
def eliminar_evento(request, evento_codigo):
    evento = Evento.objects.get(codigo=evento_codigo)
    evento.delete()
    
    return redirect('/eventos/eventos')

@verificar_autenticacion
def mis_eventos(request):
    usuario_id = request.session['usuario_id']
    usuario = Usuario.objects.get(codigo=usuario_id)

    eventos_usuario = Evento.objects.filter(encargado=usuario)

    #CONSULTA AVANZADA (CANTIDAD DE EVENTOS ORGANIZADOS)
    cantidad_eventos_usuario = eventos_usuario.count()
    #CONSULTA AVANZADA (CANTIDAD DE EVENTOS ORGANIZADOS)
    
    context = {
        'eventos_usuario': eventos_usuario,
        'usuario': usuario,
        'cantidad_eventos_usuario': cantidad_eventos_usuario,
    }
    return render(request, 'misEventos.html', context)

@verificar_autenticacion
def actualizar_mi_evento(request):
    codigo = request.POST.get('codigo')
    titulo = request.POST['titulo']
    encargado_id = request.POST['encargado']
    encargado = Usuario.objects.get(codigo=encargado_id)

    if 'imagen' in request.FILES:
        imagen = request.FILES['imagen']
    else:
        evento = Evento.objects.get(codigo=codigo)
        imagen = evento.imagen  

    fecha_evento = request.POST['fecha_evento']
    hora_evento = request.POST['hora_evento']
    descripcion = request.POST['descripcion']

    evento = Evento.objects.get(codigo=codigo)

    evento.titulo = titulo
    evento.encargado = encargado
    evento.imagen = imagen
    evento.fecha_evento = fecha_evento
    evento.hora_evento = hora_evento
    evento.descripcion = descripcion

    evento.save()

    return redirect('/eventos/miseventos/')

@verificar_autenticacion 
def eliminar_mi_evento(request, evento_codigo):
    evento = Evento.objects.get(codigo=evento_codigo)
    evento.delete()
    
    return redirect('/eventos/miseventos/')

#REGISTRAR USUARIOS EN EVENTOS 

@verificar_autenticacion
def registrar_usuario_evento(request):
    usuario_id = request.session['usuario_id']
    usuario = Usuario.objects.get(codigo=usuario_id)
    evento_id = request.POST['evento_id']
    evento = get_object_or_404(Evento, codigo=evento_id)
        
    if RegistroEvento.objects.filter(evento=evento, usuario=usuario).exists():
        messages.error(request, 'Ya estás registrado para este evento.')
    else:
        RegistroEvento.objects.create(evento=evento, usuario=usuario)
        messages.success(request, 'Te has registrado exitosamente para el evento.')
        
    return redirect('/eventos/eventos')

@verificar_autenticacion
def agregar_usuario_evento(request):
    evento_codigo = request.POST.get('codigo')
    usuario_codigo = request.POST.get('usuario_codigo')  
        
    evento = Evento.objects.get(codigo=evento_codigo)
    usuario = Usuario.objects.get(codigo=usuario_codigo)
    
    if RegistroEvento.objects.filter(evento=evento, usuario=usuario).exists():
        messages.error(request, 'El usuario ya está registrado en este evento.')
    else:
        RegistroEvento.objects.create(evento=evento, usuario=usuario)
        messages.success(request, 'Se ha registrado al usuario exitosamente.')
         
        
    return redirect('/eventos/detalle_evento/{}/'.format(evento_codigo)) 

@verificar_autenticacion
def eliminar_usuario_evento(request,usuario_codigo,evento_codigo):
    
    registro_evento = RegistroEvento.objects.get(evento=evento_codigo, usuario=usuario_codigo)
    
    registro_evento.delete()
        
    return redirect('/eventos/detalle_evento/{}'.format(evento_codigo))  

eventos/templates/detalleEvento.html
{% extends "layout.html" %}
{% block content %}
    <div class="container py-5">
        {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        <div class="d-flex justify-content-between align-items-center">
            <h1 class="text-body-tertiary">{{evento.titulo}}</h1>
            {% if es_encargado %}
                <div class="d-flex">
                    <button type="button" class="btn btn-info text-white mx-2" data-bs-toggle="modal" data-bs-target="#editarEvento">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="editarEvento" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Editar evento</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <form action="{% url 'eventos:actualizar_evento' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div>
                                        <input type="number" name="codigo" value="{{ evento.codigo}}" hidden>

                                        <div data-mdb-input-init class="form-outline mb-4">
                                            <label class="form-label">Titulo</label>
                                            <input type="titulo" class="form-control" name="titulo" value="{{evento.titulo}}"/>
                                        </div>

                                        <div data-mdb-input-init class="form-outline mb-4">
                                            <label class="form-label">Encargado</label>
                                            <input type="text" class="form-control" name="encargado" value="{{ usuario.codigo }}" readonly hidden>
                                            <input type="text" class="form-control" value="{{ usuario.nombre}} {{usuario.apellido}}" readonly>
                                        </div>
                                        
                                        <div data-mdb-input-init class="form-outline mb-4">
                                            <label class="form-label" for="customFile">Imagen </label>  
                                            <input type="file" class="form-control" name="imagen" />
                                        </div>
                    
                                        <div class="d-flex">
                                            <div data-mdb-input-init class="form-outline mb-4 pe-3">
                                                <label class="form-label">Fecha del evento</label>
                                                <input id="datepicker" name="fecha_evento" value="{{ evento.fecha_evento|date:'Y-m-d' }}" />
                                                    <script>
                                                        $('#datepicker').datepicker({
                                                            uiLibrary: 'bootstrap5',
                                                            format: 'yyyy-mm-dd'
                                                        });
                                                    </script>
                                            </div>
                                            <div data-mdb-input-init class="form-outline mb-4 mt-1 ps-3">
                                                <label class="form-label">Hora del evento</label>
                                                <input id="timepicker" name="hora_evento" value="{{evento.hora_evento}}" />
                                                    <script>
                                                        $('#timepicker').timepicker({
                                                            showMeridian: false, 
                                                            minuteStep: 1, 
                                                        });
                                                    </script>
                                            </div>
                                        </div>
                                        
                                        <div data-mdb-input-init class="form-outline mb-3">
                                            <label class="form-label">Descripcion</label>
                                            <textarea class="form-control" rows="3" name="descripcion">{{evento.descripcion}}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-info text-white">Actualizar</button>
                                    <button type="button" class="btn " data-bs-dismiss="modal">Cerrar</button>
                                </div>
                            </form>
                        </div>
                        </div>
                    </div>
                    <!-- Modal -->
                    <a href="../eliminarEvento/{{evento.codigo}}" class="btn btn-danger text-decoration-none text-white"><i class="fa-solid fa-trash"></i></a>
                </div>
            {% endif %}
        </div>
        <hr class="border border-secondary">
        <div>
            <img class="w-100 mb-1 rounded" src="{{evento.imagen.url}}">
        </div>
        <div class="d-flex text-secondary">
            <p class="pe-3 fs-6"> Fecha: {{evento.fecha_evento}}</p>
            <p class="pe-3 fs-6"> Hora: {{evento.hora_evento}}</p>
        </div>
        <div>
            <p>{{evento.descripcion}}</p>
        </div>
        <div>
            <h4 class="text-secondary">USUARIOS REGISTRADOS ({{ cantidad_usuarios_registrados }})</h4> 
            <hr>
            <div class="container">
                <div class="table-wrapper">
                    <div class="table-title">
                        <div class="d-flex justify-content-end">
                            {% if es_encargado %}
                            <div class="">
                                <button type="button" class="btn btn-secondary text-white mx-2 " data-bs-toggle="modal" data-bs-target="#agregarUsuario">
                                    <i class="fa-solid fa-user-plus"></i><span> Agregar usuario</span>
                                </button>
                                <!-- Modal -->
                                <div class="modal fade" id="agregarUsuario" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Agregar usuario</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <form action="{% url 'eventos:agregar_usuario_evento' %}" method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="modal-body">
                                                <div>
                                                    <input type="number" name="codigo" value="{{ evento.codigo}}" hidden>
            
                                                    <div data-mdb-input-init class="form-outline mb-4">
                                                        <label class="form-label">Evento</label>
                                                        <input type="titulo" class="form-control" name="titulo" value="{{evento.titulo}}"/>
                                                    </div>
            
                                                    <div class="form-outline mb-4">
                                                        <label class="form-label">Usuario</label>
                                                        <select class="form-select selectpicker" name='usuario_codigo' data-size="5">
                                                            {% for user in usuario_lista %}
                                                            <option value="{{user.codigo}}">{{user.nombre}} {{user.apellido}}</option>
                                                            {% endfor %}
                                                        </select>
                                                      </div>                                                    
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-info text-white">Agregar</button>
                                                <button type="button" class="btn " data-bs-dismiss="modal">Cerrar</button>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                </div>
                                <!-- Modal -->						
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <table class="my-3 table">
                        <thead class="table-info">
                            <tr>
                                <th>Nombre(s)</th>
                                <th>Apellido(s)</th>
                                <th>Correo electrónico</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody >
                            {% for usuario_registrado in usuarios_registrados %}
                            <tr>
                                <td>{{ usuario_registrado.nombre }}</td>
                                <td>{{ usuario_registrado.apellido  }}</td>
                                <td>{{ usuario_registrado.email }}</td>
                                <td>
                                    {% if es_encargado %}
                                    <a href="../../eliminar_usuario_evento/{{evento.codigo}}/{{usuario_registrado.codigo}}" class="btn btn-danger text-decoration-none text-white" data-toggle="modal"><i class="fa-solid fa-user-minus"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
            
        </div>
    </div>
{% endblock %}

eventos/templates/layout-before.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>

    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Tecsup</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- ========================= CSS here ========================= -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css" />

</head>

<body>

    <!-- Empezar Navegador-->
    <nav class="navbar navbar-light bg-info">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'eventos:index' %}">
                <img src="{% static 'images/logo-tecsup.png' %}" style="width: 17%" alt="Logo">
            </a>
          <div class="d-flex text-white">
            <a href="{% url 'eventos:iniciarsesion' %}" class="px-2 text-white text-decoration-none">Iniciar sesión</a>/
            <a href="{% url 'eventos:registrar' %}" class="px-2 text-white text-decoration-none">Registrarse</a>
          </div>
        </div>
    </nav>
    <!-- Terminar Navegador -->

    <!-- Block Content -->
    {% block content %} {% endblock %}
    <!-- /Block Content -->

    <!-- ========================= JS here ========================= -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

eventos/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>

    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Tecsup</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- ========================= CSS here ========================= -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.14/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.14/css/gijgo.min.css" rel="stylesheet" type="text/css" />

</head>

<body>

    <!-- Empezar Navegador-->
    <nav class="navbar navbar-light bg-info">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'eventos:eventos' %}">
                <img src="{% static 'images/logo-tecsup.png' %}" style="width: 17%" alt="Logo">
            </a>
          <div class="d-flex text-white">
            <a href="{% url 'eventos:mis_eventos' %}" class="px-2 text-white text-decoration-none">Mis eventos</a>/
            <a href="{% url 'eventos:cerrar_sesion' %}" class="px-2 text-white text-decoration-none">Cerrar sesión</a>
          </div>
        </div>
    </nav>
    <!-- Terminar Navegador -->

    <!-- Block Content -->
    {% block content %} {% endblock %}
    <!-- /Block Content -->

    <!-- ========================= JS here ========================= -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

eventos/templates/login.html
{% extends "layout-before.html" %}
{% block content %}
    {% load static %}
    <section class="vh-100">
        <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
            <img src="{% static 'images/undraw_mobile_login_re_9ntv.svg' %}" class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form action="{% url 'eventos:iniciarsesion' %}" method="post">
                    {% csrf_token %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>¡Lo sentimos!</strong> {{message}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %}
                    {% endif %}
                    <div data-mdb-input-init class="form-outline mb-4">
                        <label class="form-label">Correo electrónico</label>
                        <input type="email" class="form-control form-control-lg" name="email" />
                    </div>
        
                    <div data-mdb-input-init class="form-outline mb-3">
                        <label class="form-label">Contraseña</label>
                        <input type="password" name="contraseña" class="form-control form-control-lg"/>
                    </div>
        
                    <div class="mt-4 pt-2">
                        <button type="submit" class="btn btn-info btn-lg text-white">Iniciar sesión</button>
                        <p class="small fw-bold mt-2 pt-1 mb-0">¿No tienes una cuenta? <a href="{% url 'eventos:registrar' %}" class="link-info">Registrar</a></p>
                    </div>
        
                </form>
            </div>
        </div>
        </div>
        
    </section>
{% endblock %}